version: "3.8"
services:
  db:
    image: mysql:8.2.0
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: quilmes
      MYSQL_DATABASE: names
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
      #Por algun motivo no se puede separar la variable del valor ej: voldb: /var/lib/mysql genera un error!
      - voldb:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:5.2.1
    restart: unless-stopped
    ports:
        - 8080:80
    environment:
        # we specify that we connect to an arbitrary server with the flag below
        # "arbitrary" means you're able to specify which database server to use on login page of phpmyadmin      
        # PMA_ARBITRARY: 1
        PMA_HOST: db
        PMA_USER: user
        PMA_PASSWORD: pass
    depends_on:
      - db
  api:
    build: ./
    ports:
      - 3001:3001
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: user
      MYSQL_PASS: pass
      MYSQL_DATABASE: names
    #env_file:
    #  - .env
    depends_on:
      - db
volumes:
  voldb: